services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.multi-stage
      network: host
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_TYPE=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=school
      - DB_USER=schooluser
      - DB_PASSWORD=schoolpass
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - .:/app
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: schooluser
      POSTGRES_PASSWORD: schoolpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: