services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.multi-stage
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - DB_HOST=${LOCAL_DB_HOST}
      - DB_PORT=${LOCAL_DB_PORT}
      - DB_NAME=${LOCAL_DB_NAME}
      - DB_USER=${LOCAL_DB_USER}
      - DB_PASSWORD=${LOCAL_DB_PASSWORD}
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - .:/app
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${LOCAL_DB_NAME}
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: