version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.multi-stage
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    entrypoint: ["/app/entrypoint.sh"]