services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.multi-stage
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: schooluser
      POSTGRES_PASSWORD: schoolpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: