name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Log in to Azure
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Docker image
        run: docker build -f Dockerfile.multi-stage -t school-api:latest .

      - name: Tag Docker image
        run: docker tag school-api:latest ${{ secrets.ACR_SERVER }}/school-api:latest

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ACR_SERVER }}/school-api:latest