name: Format, Test & Coverage

on:
  pull_request:
    branches: [main]
    paths: [run.py, db/**, app/**, tests/**]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies and run ruff
        run: |
          make install
          sleep 1
          make format

      - name: Commit and push changes
        run: | 
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "ci: auto-format code with Ruff"
            git push origin HEAD:${{ github.head_ref }}
          fi
  test:
    runs-on: ubuntu-latest
    needs: format
    strategy:
      matrix:
        db: [sqlite, postgres]

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: make install

      - name: Run tests + coverage
        env:
          DATABASE_TYPE: ${{ matrix.db == 'postgres' && 'postgresql' || 'sqlite' }}
        run: |
          echo "Running pytest with coverage for ${{ matrix.db }}..."
          pytest --cov=app --cov-report=html --cov-report=term-missing --maxfail=1 -v | tee coverage_output.txt
          echo "Coverage command completed with exit code: $?"

      - name: Upload coverage artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: coverage-${{ matrix.db }}
          path: coverage_output.txt

  coverage-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Download SQLite coverage
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0
        with:
          name: coverage-sqlite
          path: ./coverage-sqlite.txt

      - name: Download Postgres coverage
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0
        with:
          name: coverage-postgres
          path: ./coverage-postgres.txt

      - name: Post PR comments
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ github.token }}
          COVERAGE_THRESHOLD: 80
        run: |
          for db in sqlite postgres; do
            COVERAGE_LINE=$(grep -E "TOTAL.*[0-9]+%" coverage-${db}.txt || true)
            if [ -z "$COVERAGE_LINE" ]; then
              echo "No coverage data for $db."
              continue
            fi
            COVERAGE_PERCENTAGE=$(echo "$COVERAGE_LINE" | awk '{print substr($NF, 1, length($NF)-1)}')
            STATUS="🔴 Fail"
            if (( $(echo "$COVERAGE_PERCENTAGE >= $COVERAGE_THRESHOLD" | bc -l) )); then
              STATUS="🟢 Pass"
            fi
            
            # Convert db name to more descriptive format
            if [ "$db" = "sqlite" ]; then
              DB_NAME="SQLite"
            else
              DB_NAME="PostgreSQL"
            fi
            
            COMMENT_BODY=$(cat <<EOF
            ### Code Coverage Summary for $DB_NAME
            | Database | Metric | Value | Status |
            |---|---|---|---|
            | $DB_NAME | Overall Coverage | ${COVERAGE_PERCENTAGE}% | ${STATUS} |
            _Threshold: ${COVERAGE_THRESHOLD}%_
            EOF
            
            gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT_BODY" --edit-last --create-if-none
          done
