name: Format, Test & Coverage

on:
  pull_request:
    branches: [main]
    paths: [run.py, db/**, app/**, tests/**]

env:
  PYTHON_VERSION: "3.12"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies and run ruff
        run: |
          make install
          sleep 1
          make format

      - name: Commit and push changes
        run: | 
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "ci: auto-format code with Ruff"
            git push origin HEAD:${{ github.head_ref }}
          fi
  test:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies and run tests
        run: |
          make install
          sleep 1
          make setup-db
          make test

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies and run coverage
        run: |
          make install
          sleep 1
          make setup-db
          make coverage > coverage_output.txt

      - name: Post comment on PR
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ github.token }}
          COVERAGE_THRESHOLD: 80
        run: |
          # Extract the percentage from the saved output
          COVERAGE_LINE=$(grep -E "TOTAL.*[0-9]+%" coverage_output.txt || true)

          if [ -z "$COVERAGE_LINE" ]; then
            echo "No coverage data found."
            exit 1
          fi

          # Parse the coverage percentage
          COVERAGE_PERCENTAGE=$(echo "$COVERAGE_LINE" | awk '{print substr($NF, 1, length($NF)-1)}')
          
          STATUS="🔴 Fail"
          if (( $(echo "$COVERAGE_PERCENTAGE >= $COVERAGE_THRESHOLD" | bc -l) )); then
            STATUS="🟢 Pass"
          fi

          COMMENT_BODY=$(cat <<EOF
          ### Code Coverage Summary
          | Metric | Value | Status |
          |---|---|---|
          | Overall Coverage | ${COVERAGE_PERCENTAGE}% | ${STATUS} |
          
          _Threshold: ${COVERAGE_THRESHOLD}%_
          EOF
          )

          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT_BODY" --edit-last --create-if-none
