name: Markdownlint

on:
  pull_request:
    paths: ["docs/*.md"]
  push:
    paths: ["docs/*.md"]
  workflow_dispatch:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint docs/*.md --fix
